# ===============================================================================================
# RUNTIME STAGE (Tối ưu cho High-load, K8s Auto-scaling & DevSecOps)
# Base: Nginx Unprivileged trên Alpine Linux (nhẹ, an toàn, chuẩn non-root K8s).
# ===============================================================================================

# Khai báo Base Image.
FROM nginxinc/nginx-unprivileged:alpine-slim

# Khai báo biến Build (ARG).
ARG APP_NAME=pos

# Gắn Metadata cho image.
LABEL maintainer="Alkaid Team" service="frontend-${APP_NAME}" environment="production"

# Tạm dùng quyền root.
USER root

# Xoá bỏ các file cấu hình mặc định rác.
RUN rm -rf /usr/share/nginx/html/* && rm /etc/nginx/conf.d/default.conf

# Trả lại quyền thực thi an toàn.
USER nginx

# Đưa cấu hình Nginx vào container.
COPY --chown=nginx:nginx default.conf /etc/nginx/conf.d/default.conf

# Đưa thành phẩm code Frontend đã build vào đúng thư mục phục vụ web.
COPY --chown=nginx:nginx ./dist/apps/${APP_NAME}/browser /usr/share/nginx/html

# Khai báo port giao tiếp.
EXPOSE 8080

# Khởi chạy Nginx Server.
CMD ["nginx", "-g", "daemon off;"]
